### ISSUE TITLE
Great experience!

### ISSUE THREAD

**Issue by songxiaoliang** [awazgyawali/rn_flutter#1]
Hi, It’s great to see the article you wrote. I am also planning to use RN and Flutter in a project at the same time. At present, my RN project volume has reached 70MB, and the function is relatively complete. After adding Flutter, the volume will be relatively expanded, which is not A trouble. I can accept. I see that the rn-flutter code on github is two years ago. Have you recently studied in depth? I really want to communicate with you, looking forward to your reply

**Comment by awazgyawali** [comment]
Sure, write to me at awazgyawali@gmail.com
